version: 0.2

env:
  variables:
    VPC_ID: VPC_ID_NOT_SET
    CLOUD9_ENVIRONMENT_ID: CLOUD9_ENVIRONMENT_ID_NOT_SET
    CFN_RESPONSE_URL: CFN_RESPONSE_URL_NOT_SET
    CFN_STACK_ID: CFN_STACK_ID_NOT_SET
    CFN_REQUEST_ID: CFN_REQUEST_ID_NOT_SET
    CFN_LOGICAL_RESOURCE_ID: CFN_LOGICAL_RESOURCE_ID_NOT_SET

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14
      python: 3.8
    commands:
      - cd $CODEBUILD_SRC_DIR/cdk/ide
      - npm install
      #- curl -sSL -o /tmp/kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      #- chmod +x /tmp/kubectl
  pre_build:
    on-failure: ABORT
    commands:
      - cd $CODEBUILD_SRC_DIR/cdk/ide
      - npm run build
      - "export AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -d: -f5)"
      - 'echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"'
      # Install CDK v2
      - npm install -g aws-cdk@next
      - npx cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION
  build:
    on-failure: ABORT
    commands:
      - cd $CODEBUILD_SRC_DIR/cdk/ide
      - "export AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -d: -f5)"
      - 'echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"'
      - 'echo "VPC ID: $VPC_ID"'
      - 'echo "CLOUD9_ENVIRONMENT_ID: $CLOUD9_ENVIRONMENT_ID"'
      - npx cdk deploy ClusterStack --require-approval never
      #- cd $CODEBUILD_SRC_DIR/cdk/pipeline
      #- pip install -t . -r requirements.txt
      #- npx cdk deploy --all --require-approval never
      #- cd $CODEBUILD_SRC_DIR/cdk/app
      #- pip install -t . -r requirements.txt
      #- npx cdk deploy --all --require-approval never
  post_build:
    on-failure: ABORT
    commands:
      - cd $CODEBUILD_SRC_DIR
      - "eval $(aws cloudformation describe-stacks --stack-name ClusterStack --query 'Stacks[0].Outputs[?contains(OutputKey, `ClusterConfigCommand`)].OutputValue' --output text | sed -e 's/--role-arn.*//')"
      #- "/tmp/kubectl delete mutatingwebhookconfigurations vpc-resource-mutating-webhook || :"
      #- "/tmp/kubectl apply -f attack/complete-demo.yaml || :"
