version: 0.2

phases:
  install:

    runtime-versions:
      python: 3.8
      nodejs: 16
    commands:
      - apt-get install -y jq
      - pip3 install checkov
      - apt-get update
      - apt-get install build-essential -y
      - apt-get install cargo -y
      - apt-get install git -y
      - curl https://sh.rustup.rs -sSf | sh -s -- -y
      - echo "Pull GA release from github"
      - echo "More info https://github.com/aws-cloudformation/cloudformation-guard/releases"
      - wget https://github.com/aws-cloudformation/cloudformation-guard/releases/download/1.0.0/cfn-guard-linux-1.0.0.tar.gz
      - echo "Extract cfn-guard"
      - tar xvf cfn-guard-linux-1.0.0.tar.gz .
  pre_build:
    commands:
      - rm -rf .python-version
  build:
    commands:
      - checkov --directory cdk.out --config-file checkov-config.yml
artifacts:
  name: scanned_source
  packaging: zip
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR