version: 0.2

phases:
  install:

    runtime-versions:
      python: 3.8
      nodejs: 16
    commands:
      - apt-get install -y jq
      - pip3 install checkov
  pre_build:
    commands:
      - rm -rf .python-version
  build:
    commands:
      - checkov --directory cdk.out --config-file checkov-config.yml
artifacts:
  name: scanned_source
  packaging: zip
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/cdk/app/